### PR TITLE
convert eyepatches and masks from headAccessory to eyewear - fixes https://github.com/HabitRPG/habitrpg/issues/3645

### LINKED ISSUE #3377: After rebirthing, headAccessory (ears, etc), "body" gear, "back" gear are not deequipped
They aren't in my equipment, and they go away if I enable use costume. I was a level 33 rogue before rebirthing.

### PR DESCRIPTION
**Pull request by Alys**
@lefnire, this requires `grunt full`
- adds new eyewear gear type
- renames headAccessory_\* images to eyewear_\* images (for eyepatches and wondercon masks only)
- changes keys in locales en file (for eyepatches and wondercon masks only)
- adds code to force Orb of Rebirth to deequip eyepatches (and headAccessories, etc) - fixes https://github.com/HabitRPG/habitrpg/issues/3377

Goes with PR https://github.com/HabitRPG/habitrpg/pull/3955

### CODE REVIEW

File: script/index.coffee [hunk 1]
```diff
@@ -461,6 +461,7 @@ api.wrap = (user, main=true) ->
         # Deequip character, set back to base armor and training sword
         gear = user.items.gear
         _.each ['equipped', 'costume'], (type) ->
+          gear[type] = {}; # deequip weapon, eyewear, headAccessory, etc, plus future new types
```
Comment (Alys) [inline script/index.coffee:464]: fixes https://github.com/HabitRPG/habitrpg/issues/3377
